### ISSUE TITLE
ability to add filters

### ISSUE THREAD

**Issue by razorg** [ravelsoft/node-jinjs#14]
Hello!

Is it possible to add filters to the environment/context?
Or if it is possible, would you document it please?

**Comment by ceymard** [comment]
I'll look into a way of doing it cleanly.

**Comment by ceymard** [comment]
For now, there is one way to do it actually ; you have to create an environment yourself with an object that has a `filter_exp` property ;

```
env = new Environment({ filter_exp: "require ('jinjs/lib/filters')" });
```

`filter_exp` is a valid javascript expression. It must resolve to an object that has filters as properties.

To use it with express, look at the `lib/express.js` file to see how the environment is set up with express. I will change this part though.

I guess you want all of jinja's regular filters ? I'm implementing them atm.

**Comment by razorg** [comment]
Thank you very much for your help!
Actually i wanted to include one of mine! That would be great.

**Comment by ceymard** [comment]
What does it do ?

Can you provide an example ?

**Comment by razorg** [comment]
some date stringify!
like {{ date|datePrint("dd-mm-yyyy") }}

**Comment by ceymard** [comment]
Nice idea.

I'm adding it as the `date` filter (I like better writing stuff like `{{ now|date("dd-mm-yyyy") }}`

**Comment by razorg** [comment]
yes, of course!
But wouldnt that require a dependency? or you're gonna implement the 
stringifyer also? :)
Anyway, you could check https://github.com/JerrySievert/node-date-utils .
or 
http://docs.python.org/library/datetime.html#strftime-strptime-behavior 
just for the string replacements.

**Comment by ceymard** [comment]
Funny, I was about to implement python's behaviour :)

Also, some of the flags (like the timezone names) will require enhanced date objects (used with the "time" module of npm).

**Comment by ceymard** [comment]
Oh, also, another idea to add your filter ;

Just do ;

```
filters = require('jinjs/lib/filters');
filters['my_filter'] = function .....
```

This should actually do the trick. Completely inelegant, but efficient. :)

**Comment by ceymard** [comment]
`date` was added with all the others filters (minus pretty print and escape control).

Not all flags work though : the week computation (lazyness) and the locale names (not directly available without a dependancy) do not work. The rest should though.

**Comment by razorg** [comment]
That's great! Love ya :)

**Comment by razorg** [comment]
well we have a workaround for the filters, so ill close the issue. consider implementing a more elegant way :)
