### ISSUE TITLE
With express you get - Maximum call stack size exceeded when running

### ISSUE THREAD

**Issue by kmpm** [ravelsoft/node-jinjs#19]
## Steps to reproduce
1. cd test/express
2. coco app.co
## Expected results

All tests honored
## Actual results

4 honored and 2 broken.

The jinja templates in Express can use its own include facility
    test
      "Hello World." == "RangeError: Maximum call stack size exceeded"

The jinja templates in Express can use its own include facility
     test
      "Hello World." == "RangeError: Maximum call stack size exceeded"
## Environment
- Ubuntu 11.04
- node v0.6.0
- jinjs 0.3.3

**Comment by lemieux** [comment]
I get exactly the same problem with Ubuntu 11.10, node v0.06.0 and jinjs 0.3.3.

In my template, I only have a Hello World in the body part.

**Comment by kmpm** [comment]
It seems to be related to {% extends %} 
Without that my templates render correct.

**Comment by lemieux** [comment]
I confirmed.

**Comment by ceymard** [comment]
This was actually fixed in my last commit, forgot to bump the version.

0.3.4 should behave correctly.

**Comment by ceymard** [comment]
Also, I do not seem to receive mails from the issues here, which is why it took so long to respond... Sorry about that, I'm gonna see what I can do about that.
