### ISSUE TITLE
use jinjs with express, errors occured

### ISSUE THREAD

**Issue by ghost** [ravelsoft/node-jinjs#21]
500 TypeError: object is not a function
at ExpressEnvironment.CALL_NON_FUNCTION (native)
at ExpressEnvironment.getTemplateFromString (/usr/local/lib/node_modules/jinjs/lib/express.js:34:82)
at Object.compile (/usr/local/lib/node_modules/jinjs/lib/express.js:64:45)
at Function.compile (/usr/local/lib/node_modules/locomotive/node_modules/express/lib/view.js:68:33)
at ServerResponse._render (/usr/local/lib/node_modules/locomotive/node_modules/express/lib/view.js:417:18)
at ServerResponse.render (/usr/local/lib/node_modules/locomotive/node_modules/express/lib/view.js:318:17)

who can explain that?

Jinjs: 0.3.5
Express: 2.5.6
Node: 0.6.7
OS: Debian

**Comment by ceymard** [comment]
Can you give me a way to reproduce the error so that I can look into it ?

**Comment by ghost** [comment]
I modify the lib/express.js at the line 34 as res = expressEnvironment.superclass.prototype.getTemplateFromString.call(this, str, ctx);

the original is :         res = ExpressEnvironment.superclass.prototype.getTemplateFromString.call.call(this, this, str, ctx);

the same as lib/express.js line 23: return ExpressEnvironment.superclass.prototype.trackFile.call(this, path);

all is OK!!

The way is following your guide:
#npm install jinjs

and my express config is that:
var jinja = require('jinjs');
app.register('.html', jinja);
app.set('views', __dirname + '/../../app/views');
app.set('view engine', 'html');
this.set('view options', {layout: false});

and I DON'T use precompiling with pwilang, because if use, it issued some other bug as followings:

layout.html:

&lt;!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml"&gt;
&lt;head&gt;
    &lt;title&gt;{% block title %}{{PAGE_TITLE}} | {{ SITE_TITLE }}{% endblock %}&lt;/title&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /&gt;
        ....
    &lt;style type="text/css"&gt;
    #page {
        margin-top: 0;
    }
    &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;div id="page" class="container "&gt;
        &lt;div id="header"&gt;
            {% block header %}
            {% include "../common/header.html" %}
            {% endblock %}
        &lt;/div&gt;
        &lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;

and the css style part in the ultimate rendered page will be like this:
.....

&lt;style type="text/css"&gt;
    &lt;div id="page"&gt;{
        margin-top: 0;
    }
&lt;/style&gt;

....

when I disable pre-compiling, the problem gone!

**Comment by ceymard** [comment]
I'm going to remove the pwilang precompilation entirely, as it obviously only is confusing...

**Comment by ceymard** [comment]
Latest version should work.

**Comment by ghost** [comment]
OK, thanks. All work now.

This issue can be closed
