### ISSUE TITLE
directory layout and/or package.json wrong possibly?

### ISSUE THREAD

**Issue by thetrippy** [ravelsoft/node-jinjs#23]
While attempting to use the jinjs package for the first time via npm install

```
npm install jinjs

coffee test.coffee 
Error: Cannot find module 'jinjs'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)

   <snip>Im paranoid about file paths :)</snip>
```

``` coffeescript
# contents of test.coffee
jinjs = require "jinjs"

```

I was able to get it working by simply creating symlink to tball/lib

```
ln -s tball/lib/ lib
```

**Comment by ceymard** [comment]
gah.
I have no idea what's happening, I'll look into it.

**Comment by ceymard** [comment]
I think this is a problem that arises with npm and .gitignore files : since I ignore lib/ (which is the compiled files directory), I think it just blacklists everything.

Gonna look into it whenever I have time. Or if you're up to it, this would be fantastic.

**Comment by ceymard** [comment]
Actually, I think I just would have to create a .npmignore, commit it, and push the package again.

**Comment by ceymard** [comment]
I just fixed it
