### ISSUE TITLE
npm install is broken.

### ISSUE THREAD

**Issue by thetrippy** [ravelsoft/node-jinjs#25]
I tested git version vs npm install.

The two issues i noticed when using npm install

Cannot require without modifying package.json.  I have posted this bug in another ticket.

```
TypeError: object is not a function
    at ExpressEnvironment.CALL_NON_FUNCTION (native)
```

This happens while requesting a simple page.

If i clone jinjs from git,  and install its dependencies via npm the parser works correctly.

**Comment by ceymard** [comment]
I probably forgot to update the npm version.

**Comment by ceymard** [comment]
I just fixed that.
